title: "Sumit Kumar"
description: "Building Digital Solutions for Online Businesses"
theme: jekyll-theme-cayman

url: "https://ksumit-webdeveloper.github.io"
author: 
  name: "Sumit Kumar"
  email: "sumit.srcm@gmail.com"

show_downloads: false

# Navigation Links
navbar-links:
  About Me: "#about"
  Websites I've Developed: "#projects"
  Blog: "#blog"
  Pricing: "#pricing"
  Contact: "#contact"

# Plugins (optional but helps Pages render properly)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
